//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NunitTemaTests
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjektiMikrotezesEntities : DbContext
    {
        public ProjektiMikrotezesEntities()
            : base("name=ProjektiMikrotezesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Perdoruesit> Perdoruesits { get; set; }
        public virtual DbSet<Rolet> Rolets { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
